chats/urls.py
from django.urls import path , include
from . import views

urlpatterns = [

  path('post_feedback', views.post_feedback, name='post_feedback'),
  path('get_feedback', views.get_feedback, name='get_feedback')
   
]

disease_prediction/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main_app.urls")),
     path("accounts/", include("accounts.urls")),
     path("", include("chats.urls"))
]

main_app/models.py
from django.db import models

from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField

from datetime import date


#user = models.OneToOneField(settings.AUTH_USER_MODEL)

class patient(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    
    is_patient = models.BooleanField(default=True)
    is_doctor = models.BooleanField(default=False)

    name = models.CharField(max_length = 50)
    dob = models.DateField()
    address = models.CharField(max_length = 100)
    mobile_no = models.CharField(max_length = 15)
    gender = models.CharField(max_length = 10)

    
    @property
    def age(self):
        today = date.today()
        db = self.dob
        age = today.year - db.year
        if today.month < db.month or today.month == db.month and today.day < db.day:
            age -= 1
        return age 



class doctor(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    
    is_patient = models.BooleanField(default=False)
    is_doctor = models.BooleanField(default=True)

    name = models.CharField(max_length = 50)
    dob = models.DateField()
    address = models.CharField(max_length = 100)
    mobile_no = models.CharField(max_length = 15)
    gender = models.CharField(max_length = 10)

    registration_no = models.CharField(max_length = 20)
    year_of_registration = models.DateField()
    qualification = models.CharField(max_length = 20)
    State_Medical_Council = models.CharField(max_length = 30)

    specialization = models.CharField(max_length = 30)

    rating = models.IntegerField(default=0)





class diseaseinfo(models.Model):

    patient = models.ForeignKey(patient , null=True, on_delete=models.SET_NULL)

    diseasename = models.CharField(max_length = 200)
    no_of_symp = models.IntegerField()
    symptomsname = ArrayField(models.CharField(max_length=200))
    confidence = models.DecimalField(max_digits=5, decimal_places=2)
    consultdoctor = models.CharField(max_length = 200)



class consultation(models.Model):

    patient = models.ForeignKey(patient ,null=True, on_delete=models.SET_NULL)
    doctor = models.ForeignKey(doctor ,null=True, on_delete=models.SET_NULL)
    diseaseinfo = models.OneToOneField(diseaseinfo, null=True, on_delete=models.SET_NULL)
    consultation_date = models.DateField()
    status = models.CharField(max_length = 20)





class rating_review(models.Model):

    patient = models.ForeignKey(patient ,null=True, on_delete=models.SET_NULL)
    doctor = models.ForeignKey(doctor ,null=True, on_delete=models.SET_NULL)
    
    rating = models.IntegerField(default=0)
    review = models.TextField( blank=True ) 


    @property
    def rating_is(self):
        new_rating = 0
        rating_obj = rating_review.objects.filter(doctor=self.doctor)
        for i in rating_obj:
            new_rating += i.rating
       
        new_rating = new_rating/len(rating_obj)
        new_rating = int(new_rating)
        
        return new_rating

templates/doctor/view_profile/view_profile.html
{% extends "basic.html" %}
{% load static %}

 
	{% block head %}


  <link rel="stylesheet" href="{% static 'doctor/view_profile/forms.css' %}">
  <link rel="stylesheet" href="{% static 'doctor/view_profile/responsive.css' %}">
  <link rel="stylesheet" href="{% static 'doctor/view_profile/base.css' %}">



{% endblock %}




{% block body %}


    <!-- Content -->
    <div id="content" class="colM">
        
        <div id="content-main">

<fieldset class="module aligned " >

<div class="border border-dark rounded-lg mx-auto mt-3 " style="width:600px">

<div class="container mt-3 "  >

  <div class="mx-auto text-center"><h2 >          Doctor Profile - {{ duser.doctor.name }} </h2> 
  </div>




  <div class="form-row field-username">


        <div>
            
            
                <label class="required" for="id_username">username:</label>
                
                    <input type="text" name="username" value={{duser.username}} class="vTextField" maxlength="50" required="" id="id_username">
                
            
            
        </div>
    
    </div>

    
<div class="form-row field-name">


    <div>
        
        
            <label class="required" for="id_name">Name:</label>
            
                <input type="text" name="name" value={{duser.doctor.name}} class="vTextField" maxlength="50" required="" id="id_name">
            
        
        
    </div>

</div>



<div class="form-row field-email">


        <div>
            
            
                <label class="required" for="id_email">Email:</label>
                
                    <input type="text" name="email" value={{duser.email}} class="vTextField" maxlength="100" required="" id="id_email">
                
            
            
        </div>
    
    </div>
    

<div class="form-row field-dob">


    <div>
        
        
            <label class="required" for="id_dob">Dob:</label>
            
                <input type="text" name="dob" value={{duser.doctor.dob|date:'Y-m-d'}} class="vDateField" size="10" required="" id="id_dob">
  </div>

</div>

<div class="form-row field-img">


    <div>
        
        
            <label for="id_img">Img:</label>
            
                <input type="file" name="img" accept="image/*" id="id_img">
            
        
        
    </div>

</div>

<div class="form-row field-address">


    <div>
        
        
            <label class="required" for="id_address">Address:</label>
            
                <input type="text" name="address" value={{duser.doctor.address}} class="vTextField" maxlength="100" required="" id="id_address">
            
        
        
    </div>

</div>

<div class="form-row field-mobile_no">


    <div>
        
        
            <label class="required" for="id_mobile_no">Mobile no:</label>
            
                <input type="text" name="mobile_no" value={{duser.doctor.mobile_no}} class="vTextField" maxlength="15" required="" id="id_mobile_no">
            
        
        
    </div>

</div>

<div class="form-row field-gender">


    <div>
        
        
            <label class="required" for="id_gender">Gender:</label>
            
                <input type="text" name="gender" value={{duser.doctor.gender}} class="vTextField" maxlength="10" required="" id="id_gender">
            
        
        
    </div>

</div>

<div class="form-row field-registration_no">


    <div>
        
        
            <label class="required" for="id_registration_no">Registration no:</label>
            
                <input type="text" name="registration_no" value={{duser.doctor.registration_no}} class="vTextField" maxlength="20" required="" id="id_registration_no">
            
        
        
    </div>

</div>

<div class="form-row field-year_of_registration">


    <div>
        
        
            <label class="required" for="id_year_of_registration">Year of registration:</label>
            
                <input type="text" name="year_of_registration" value={{duser.doctor.year_of_registration|date:'Y-m-d'}} class="vDateField" size="10" required="" id="id_year_of_registration">
  </div>
</div>


<div class="form-row field-qualification">


    <div>
        
        
            <label class="required" for="id_qualification">Qualification:</label>
            
                <input type="text" name="qualification" value={{duser.doctor.qualification}} class="vTextField" maxlength="20" required="" id="id_qualification">
            
        
        
    </div>

</div>

<div class="form-row field-State_Medical_Council">


    <div>
        
        
            <label class="required" for="id_State_Medical_Council">State Medical Council:</label>
            
                <input type="text" name="State_Medical_Council" value={{duser.doctor.State_Medical_Council}} class="vTextField" maxlength="30" required="" id="id_State_Medical_Council">
            
        
        
    </div>

</div>

<div class="form-row field-specialization">


    <div>
        
        
            <label class="required" for="id_specialization">Specialization:</label>
            
                <input type="text" name="specialization" value={{duser.doctor.specialization}} class="vTextField" maxlength="30" required="" id="id_specialization">
            
        
        
    </div>

</div>
<div class="form-row field-rating">


        <div>
            
            
                <label class="required" for="id_specialization">Rating:</label>
                
                    <input type="text" name="Rating" value={{duser.doctor.rating}}/5 class="vTextField" maxlength="30" required="" id="id_Rating">
                
            
            
        </div>
    
</div>

{% if request.user.doctor %}

            <div class="comtainer mt-3 mb-3 ml-4 mr-4">
              
                <div class="btn-group">
                  <button type="button" class="btn btn-secondary pr-4 pl-4 mr-5 ml-5 " data-toggle="collapse" data-target="#save">Edit</button>
                  <div id="save" class="collapse ml-5 mr-5">
                    <button type="button"  id="save" class="btn btn-success pr-4 pl-4 mr-5 ml-5 ">Save</button>
                    </div>
                 
                </div>
                
            </div>
      {% endif %}


</div>


</fieldset>


<div class="container">
        
    <br>   
<h2>Ratings and Reviews</h2>
<br>
        <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Patient name</th>
                    <th>Ratings</th>
                    <th>Reviews</th>
                  </tr>
                </thead>
                <tbody>
                        {% for i in rate %}
               <tr>
                    <td>{{i.patient.name}}</td>
                    <td>{{i.rating}}/5</td>
                    <td>{{i.review}}</td>
               </tr>
                 
     {% endfor %}
                </tbody>
              </table>
</div>


    </div>

 </div>
    <!-- END Content -->

</div>
<!-- END Container -->







<script>

    $(document).ready( function(){
      $('#save').click( function(event){
  
      dob = document.getElementById('id_dob').value,
      yor = document.getElementById('id_year_of_registration').value,
  
      $.ajax({
          url :"{% url 'saveddata' duser.username %}",
          type : "POST",
          data : { 
  
          'csrfmiddlewaretoken': '{{ csrf_token }}',
          "name" :document.getElementById('id_name').value,
          "dob" :dob,
          "gender" :document.getElementById('id_gender').value,
          "address" :document.getElementById('id_address').value,
          "mobile_no" :document.getElementById('id_mobile_no').value,
          "registration_no" : document.getElementById('id_registration_no').value,
          "year_of_registration" : yor,
          "qualification": document.getElementById('id_qualification').value,
          "State_Medical_Council" : document.getElementById('id_State_Medical_Council').value,
          "specialization" : document.getElementById('id_specialization').value
          
  
         },
  
          success : function(){
            alert("new data is saved.")
          }
  
      });
  
  
    });
  });
  
  </script>
  
{% endblock %}